#!/bin/sh

# Code from Apache Tomcat
# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi  
done

PRGDIR=`dirname "$PRG"`

PGPASSWORD="sa"
export PGPASSWORD

java -Dh2.bindAddress=127.0.0.1 -cp "$PRGDIR"/lib/find2.jar:"$PRGDIR"/lib/h2-1.3.154.jar net.jumperz.app.MFind2.MFind2 "$PWD" "$@" >/dev/null & 
PGPORT=`java -cp "$PRGDIR"/lib/find2.jar net.jumperz.app.MFind2.MLauncher`

export PGPORT
psql --quiet -h localhost -U sa find2.$PGPORT
echo "select shutdownFind2();"        | psql -h localhost -U sa find2.$PGPORT >/dev/null
echo "DROP ALL OBJECTS DELETE FILES;" | psql -h localhost -U sa find2.$PGPORT >/dev/null
